In [0]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [0]:
env = gym.make("FrozenLake-v0")

In [42]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size , action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [44]:
rewards_all_episodes = []
#Q Learning Algorithm
for episode in range(num_episodes):
  state = env.reset()
  done = False
  rewards_current_episode = 0
  for step in range(max_steps_per_episode):
    #Exploitation Exploration trade off
    exploration_rate_threshold = random.uniform(0,1)
    if exploration_rate_threshold > exploration_rate:
      action = np.argmax(q_table[state,:])
    else:
      action = env.action_space.sample()
    new_state, reward, done, info = env.step(action)
    q_table[state,action] = q_table[state,action]*(1 - learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state ,:]))
    state = new_state
    rewards_current_episode+= reward
    if done== True:
      break
  #Exploration Rate Decay
  exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)*np.exp(- exploration_decay_rate * episode)
  rewards_all_episodes.append(rewards_current_episode)
#Calculate and Print the Average Reward per 1000 Episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1
print("AVERAGE REWARD PER 1000 EPISODES\n")
for r in rewards_per_thousand_episodes:
  print(count,"th thousand : ",str(sum(r/1000)))
  count+= 1
#Print Updated Q Table
print("UPDATED Q TABLE\n")
print(q_table)

AVERAGE REWARD PER 1000 EPISODES

1 th thousand :  0.04300000000000003
2 th thousand :  0.20700000000000016
3 th thousand :  0.3870000000000003
4 th thousand :  0.5590000000000004
5 th thousand :  0.6240000000000004
6 th thousand :  0.6590000000000005
7 th thousand :  0.6530000000000005
8 th thousand :  0.6720000000000005
9 th thousand :  0.6610000000000005
10 th thousand :  0.7050000000000005
UPDATED Q TABLE

[[0.54484091 0.52284513 0.51580661 0.5149513 ]
 [0.36723044 0.34095183 0.25713552 0.49437297]
 [0.40230025 0.36516898 0.38362779 0.47233202]
 [0.26389951 0.38787334 0.35458779 0.45393562]
 [0.56014109 0.44183857 0.37301992 0.411115  ]
 [0.         0.         0.         0.        ]
 [0.45729527 0.16865876 0.22950303 0.16568492]
 [0.         0.         0.         0.        ]
 [0.44740511 0.32628963 0.37624879 0.59037865]
 [0.49706952 0.63991936 0.42522254 0.33537251]
 [0.63738567 0.395275   0.39243336 0.34794766]
 [0.         0.         0.         0.        ]
 [0.         0.       

In [45]:
for episode in range(3):
  state = env.reset()
  done = False
  print("EPISODE : ",episode+1,"\n")
  time.sleep(1)
  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)
    action = np.argmax(q_table[state,:])
    new_state,reward,done,info = env.step(action)
    if done:
      clear_output(wait=True)
      env.render()
      if reward == 1:
        print("YOU REACHED THE GOAL!\n")
        time.sleep(3)
      else:
        print("YOU FELL THROUGH A HOLE!\n")
        time.sleep(3)
      clear_output(wait=True)
      break
    state = new_state
env.close()


  (Down)
SFFF
FHFH
FFFH
HFFG
YOU REACHED THE GOAL!

